/*********************************************************************************/
/************ THIS FILE IS GENERATED BY AWTK DESIGNER, DO NOT MODIFY *************/
/*********************************************************************************/
#include "awtk.h"
#include "../res/assets.inc"

extern ret_t application_init(void);

extern ret_t application_exit(void);

extern ret_t application_on_cmd_line(int argc, char* argv[]);

#define ON_CMD_LINE application_on_cmd_line

#include "awtk_main.inc"
