import os
import sys
import platform

OS_NAME = platform.system();
LIB_DIR=os.environ['LIB_DIR'];
BIN_DIR=os.environ['BIN_DIR'];

env=DefaultEnvironment().Clone()
SOURCES=Glob('coin3d/*.c')+Glob('coin3d/*.cpp')+Glob('*.c')+Glob('*.cpp')

# AWTK glad is compiled into Coin4d.dll and exported (GLAD_GLAPI_EXPORT).
# coin3d.dll must dllimport those pointers instead of compiling a second copy.
if OS_NAME == 'Windows':
  env.Append(CPPDEFINES=['GLAD_GLAPI_EXPORT'])

EXPORT_DEF=''
if OS_NAME == 'Windows' :
  if os.environ['TOOLS_NAME'] == '' :
    EXPORT_DEF = ' /DEF:"src/coin3d.def" '
  elif os.environ['TOOLS_NAME'] == 'mingw' :
    EXPORT_DEF = ' "src/coin3d.def" '

if 'BUILD_SHARED' in os.environ and os.environ['BUILD_SHARED'] == 'True':
  coin_lib = os.environ.get('COIN_LINK_NAME', 'Coin')
  LIBS=[coin_lib, 'awtk']
  LINKFLAGS=env['LINKFLAGS'] + EXPORT_DEF
  env.SharedLibrary(os.path.join(BIN_DIR, 'coin3d'), SOURCES, LIBS=LIBS, LINKFLAGS=LINKFLAGS);
else:
  env.Library(os.path.join(LIB_DIR, 'coin3d'), SOURCES);
